module.exports = {
    COLLATERAL_SYMBOL: "",
    COLLATERAL_DECIMALS: 18,
    COLLATERAL_ADDRESS: "",
  
    DIAMOND_ADDRESS: "",
    MULTI_ACCOUNT_ADDRESS: "",
    PARTY_B_WHITELIST: "",
    SIGNATURE_STORE_ADDRESS: "",
  
    MULTICALL3_ADDRESS: "",
    USDC_ADDRESS: "",
    WRAPPED_NATIVE_ADDRESS: "",
    ANALYTICS_SUBGRAPH_ADDRESS: "",
    ORDER_HISTORY_SUBGRAPH_ADDRESS: "",
    HEDGER_URL: '',
};